apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hera-role-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: hera-service-account
  namespace: argo
roleRef:
  kind: Role
  name: hera-role
  apiGroup: rbac.authorization.k8s.io
