apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hera-role
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers", "workflowtemplates", "cronworkflows"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
